spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/skep_local
    username: skep_user_local
    password: 1111
  sql:
    init:
      mode: always
      schema-locations: classpath:/db/schema.sql
      data-locations: classpath:/db/data.sql

logging:
  level:
    root: INFO
    org.jetbrains.exposed.sql: DEBUG              # Exposed SQL 로그 활성화
    org.jetbrains.exposed.sql.transactions: DEBUG # Exposed 트랜잭션 로그 활성화

